# Generated by Django 5.1 on 2026-01-31 17:38

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media/', location='/app/protected_media'), upload_to='cosmetologist_docs/', verbose_name='Документ'),
        ),
    ]
