# Generated by Django 5.2.11 on 2026-02-07 21:30

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_license_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='is_cosmetologist',
            field=models.BooleanField(default=False, verbose_name='Является косметологом'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_manicurist',
            field=models.BooleanField(default=False, verbose_name='Является мастером маникюра'),
        ),
        migrations.AddField(
            model_name='user',
            name='requested_role',
            field=models.CharField(blank=True, choices=[('cosmetologist', 'Косметолог'), ('manicurist', 'Мастер маникюра/педикюра')], max_length=20, null=True, verbose_name='Запрошенная роль'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('none', 'Нет заявки'), ('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='none', max_length=20, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media/', location='/app/protected_media'), upload_to='cosmetologist_docs/', verbose_name='Документ об образовании'),
        ),
    ]
