# Generated by Django 5.2.11 on 2026-02-16 18:12

import django.contrib.auth.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_status_user_is_cosmetologist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Заявка на профи',
                'verbose_name_plural': 'Заявки на профи (Очередь)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='is_cosmetologist',
            field=models.BooleanField(default=False, verbose_name='Доступ: Косметолог'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_manicurist',
            field=models.BooleanField(default=False, verbose_name='Доступ: Маникюр'),
        ),
        migrations.AlterField(
            model_name='user',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media/', location='/app/protected_media'), upload_to='cosmetologist_docs/', verbose_name='Документ (Диплом)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='requested_role',
            field=models.CharField(blank=True, choices=[('cosmetologist', 'Косметолог'), ('manicurist', 'Мастер маникюра/педикюра')], max_length=20, null=True, verbose_name='Запрашиваемая роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('none', 'Нет активной заявки'), ('pending', 'На проверке'), ('approved', 'Одобрено (Архив)'), ('rejected', 'Отклонено (Архив)')], default='none', max_length=20, verbose_name='Статус текущей заявки'),
        ),
    ]
