# Generated by Django 5.2.11 on 2026-02-16 18:23

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_prorequest_alter_user_is_cosmetologist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('cosmetologist', 'Косметолог'), ('manicurist', 'Мастер маникюра/педикюра')], max_length=20, verbose_name='Роль')),
                ('license_photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media/', location='/app/protected_media'), upload_to='cosmetologist_docs/', verbose_name='Документ')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
            ],
            options={
                'verbose_name': 'Заявка на профи',
                'verbose_name_plural': 'Заявки на профи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProRequest',
        ),
        migrations.RemoveField(
            model_name='user',
            name='license_photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='requested_role',
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('none', 'Нет активной заявки'), ('pending', 'На проверке')], default='none', max_length=20, verbose_name='Статус проверки'),
        ),
        migrations.AddField(
            model_name='proapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
