# Generated by Django 5.1 on 2026-01-20 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа фильтров',
                'verbose_name_plural': 'Группы фильтров',
            },
        ),
        migrations.CreateModel(
            name='FilterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.filtergroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Значение фильтра',
                'verbose_name_plural': 'Значения фильтров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_retail', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (розница)')),
                ('price_pro', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (для косметологов)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Остаток на складе')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение товара')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filters', models.ManyToManyField(blank=True, related_name='products', to='products.filtervalue', verbose_name='Фильтры')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
