# Generated by Django 5.1 on 2026-01-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок (для админки)')),
                ('image', models.ImageField(upload_to='carousel/', verbose_name='Изображение баннера')),
                ('link', models.CharField(blank=True, help_text='Например: / или https://google.com', max_length=255, verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Слайд карусели',
                'verbose_name_plural': 'Слайды карусели',
                'ordering': ['order'],
            },
        ),
    ]
