# Generated by Django 5.2.10 on 2026-02-01 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_carouselitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название раздела')),
                ('slug', models.SlugField(help_text='Например: face, body, sets', unique=True, verbose_name='URL (ссылка)')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем левее в меню', verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Раздел (Категория)',
                'verbose_name_plural': 'Разделы (Категории)',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='carouselitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='carouselitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='Новинка'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=models.ImageField(upload_to='carousel/', verbose_name='Картинка слайда'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='link',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка при клике'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='filtervalue',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.filtergroup'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filters',
            field=models.ManyToManyField(blank=True, to='products.filtervalue', verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_pro',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (ПРО)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_retail',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (Розница)'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Раздел'),
        ),
    ]
