# Generated by Django 5.2.11 on 2026-02-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_pro',
        ),
        migrations.AddField(
            model_name='product',
            name='price_cosmetology',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена (Косметолог)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price_manicure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена (Маникюр/Педикюр)'),
        ),
    ]
