# Generated by Django 5.2.11 on 2026-02-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_price_pro_product_price_cosmetology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок вывода'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_cosmetology',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (Косметолог)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_manicure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (Маникюр/Педикюр)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_retail',
            field=models.DecimalField(decimal_places=2, help_text='Обязательная цена для всех', max_digits=10, verbose_name='Цена (Розничная)'),
        ),
    ]
